/**
 * Upload history item type and pure CRUD helper functions.
 *
 * This module is framework-agnostic. For a reactive Svelte store wrapper
 * see the `svelte/` sub-package.
 */

import type { ImageMetadataInput } from './metadata';

/**
 * A single entry in the local upload history.
 * Tracks the original upload tags (including preview references) as well
 * as optionally enriched metadata and published Nostr event IDs.
 */
export interface UploadHistoryItem {
  /** Primary URL of the uploaded file */
  url: string;
  /** MIME type of the file */
  mime?: string;
  /** ISO 8601 timestamp of the upload */
  createdAt: string;
  /** SHA-256 hash of the original file (from the `x` tag) */
  sha256?: string;
  /** Tags returned from the upload, including thumb / image preview refs */
  uploadTags?: string[][];
  /** File metadata entered or generated by the user */
  metadata?: ImageMetadataInput;
  /** Nostr event kinds that have been published for this upload */
  publishedKinds?: number[];
  /** Event IDs of published Nostr events (kind 1063, kind 1, …) */
  publishedEventIds?: string[];
}

/**
 * Add a new item at the front of the history array.
 * Returns a new array (does not mutate the original).
 */
export function addHistoryItem(
  history: UploadHistoryItem[],
  item: UploadHistoryItem,
): UploadHistoryItem[] {
  return [item, ...history];
}

/**
 * Update the first entry with the given URL.
 * `publishedEventIds` is merged (appended) rather than replaced.
 * Returns a new array (does not mutate the original).
 */
export function updateHistoryItemByUrl(
  history: UploadHistoryItem[],
  url: string,
  updates: Partial<
    Pick<
      UploadHistoryItem,
      'mime' | 'metadata' | 'publishedKinds' | 'publishedEventIds' | 'sha256' | 'uploadTags'
    >
  >,
): UploadHistoryItem[] {
  const index = history.findIndex((item) => item.url === url);
  if (index < 0) return history;

  const nextHistory = [...history];
  const existing = nextHistory[index];
  nextHistory[index] = {
    ...existing,
    ...updates,
    publishedEventIds: [
      ...(existing.publishedEventIds ?? []),
      ...(updates.publishedEventIds ?? []),
    ],
  };

  return nextHistory;
}

/**
 * Remove all entries with the given URL.
 * Returns a new array (does not mutate the original).
 */
export function removeHistoryItemByUrl(
  history: UploadHistoryItem[],
  url: string,
): UploadHistoryItem[] {
  return history.filter((item) => item.url !== url);
}
